const $=s=>document.querySelector(s);
let registry={agents:[]},runtime=null,jurisdictions=null;
const DEPTS=['Opportunity Intelligence','Procurement Operations','Vendor Research','Proposal Studio','Compliance & Risk','Pricing & Finance','Outreach','Contracts & Delivery'];
const REGION_POS={TX:[23,29],DC:[77,29],MD:[23,70],VA:[77,70]};
const REGION_COLOR={TX:'#20d6ff',DC:'#9a72ff',MD:'#2ee69f',VA:'#f2c14e'};
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function specialistState(){const vals=Object.values(runtime?.agentStates||{});return {working:vals.filter(v=>v==='working').length,waiting:vals.filter(v=>v==='awaiting_approval').length,idle:vals.filter(v=>v==='live_idle').length,blocked:vals.filter(v=>v==='blocked').length}}
function regionalState(code){const feed=runtime?.integrations?.procurementFeeds;return feed?'connected':'attention'}
function renderRegional(){
  const root=$('#regionalAgents'),svg=$('#lines');root.innerHTML='';svg.querySelectorAll('.live-path').forEach(x=>x.remove());
  (jurisdictions?.priority||[]).forEach((r,i)=>{
    const [x,y]=REGION_POS[r.code],color=REGION_COLOR[r.code],state=regionalState(r.code);
    const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.classList.add('live-path');path.setAttribute('d',`M ${x/100*900} ${y/100*500} Q 450 250 450 250`);svg.append(path);
    const node=document.createElement('button');node.className=`regional-agent ${state}`;node.style.left=x+'%';node.style.top=y+'%';node.style.setProperty('--region',color);node.innerHTML=`<span class="region-orbit"></span><span class="region-bot"><i class="antenna"></i><span class="region-head"><i></i><i></i></span><span class="region-body"></span><span class="region-arm left"></span><span class="region-arm right"></span></span><span class="region-desk"><i class="screen"></i></span><strong>${esc(r.employee)}</strong><small>${esc(r.name)}</small><em>${state==='connected'?'Connected · monitoring':'Attention required'}</em>`;node.onclick=()=>showRegion(r);root.append(node);
  });
}
function renderStatus(){
  const p=runtime?.progress||{},apps=runtime?.approvals||[],events=runtime?.events||[],s=specialistState(),readyRegions=(jurisdictions?.priority||[]).filter(r=>regionalState(r.code)==='connected').length;
  $('#regionalReady').textContent=`${readyRegions} / 4`;$('#systemState').textContent=readyRegions===4?'All Priority Markets Connected':'Attention Required';$('#backgroundReady').textContent=Math.max(0,(runtime?.readyAgents||0)-1);$('#blockedCount').textContent=s.blocked;$('#queueDepth').textContent=runtime?.queueDepth||0;$('#availability').textContent=runtime?'ONLINE':'ERROR';$('#reviewBadge').textContent=`${apps.length} decision${apps.length===1?'':'s'}`;
  $('#regionalMini').innerHTML=(jurisdictions?.priority||[]).map(r=>`<span><i class="${regionalState(r.code)}"></i><b>${r.code}</b><small>${regionalState(r.code)==='connected'?'Live':'Attention'}</small></span>`).join('');
  $('#progress').innerHTML=[['Opportunities Found',p.found||0],['Qualified',p.qualified||0],['Proposals in Progress',p.proposals||0],['Submitted',p.submitted||0],['Approvals Pending',apps.length]].map(x=>`<li>${x[0]} <b>${x[1]}</b></li>`).join('');
  $('#approvals').innerHTML=apps.length?apps.slice(0,3).map(x=>`<div><b>${esc(x.title)}</b><p>${esc(x.summary||'Executive decision required')}</p></div>`).join(''):'<div><b>No executive decisions waiting</b><p>Decision packets will appear here when specialist work reaches the final gate.</p></div>';
  $('#activity').innerHTML=events.length?events.slice(0,12).map(e=>`<div><time>${new Date(e.created_at).toLocaleTimeString('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'})}</time><span>${esc(e.message)}</span><b class="verified">VERIFIED</b></div>`).join(''):'<div><time>NOW</time><span>No verified execution events yet.</span><b class="waiting">IDLE</b></div>';
  $('#specialistSummary').innerHTML=DEPTS.map(d=>{const members=registry.agents.filter(a=>a.department===d);const working=members.filter(a=>runtime?.agentStates?.[a.id]==='working').length;return `<span><b>${esc(d)}</b><small>${working?working+' working now':members.length+' ready in background'}</small></span>`}).join('');
  document.body.classList.toggle('has-approval',apps.length>0);
}
function renderCycles(){const times=jurisdictions?.scheduledCycles?.times||[];const now=new Date(),parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now),hm=Number(parts.find(x=>x.type==='hour').value)*60+Number(parts.find(x=>x.type==='minute').value);let next=times.find(t=>{const [h,m]=t.split(':').map(Number);return h*60+m>hm});if(!next)next=times[0]+' tomorrow';const display=next.includes('tomorrow')?'8:00 AM tomorrow':formatTime(next);$('#nextRun').textContent=display;$('#nextRunSmall').textContent=display;$('#countdown').textContent=next.includes('tomorrow')?'Tomorrow':`${Math.max(0,(()=>{const[h,m]=next.split(':').map(Number);return h*60+m-hm})())} min`;$('#cycleList').innerHTML=times.map(t=>{const[h,m]=t.split(':').map(Number),v=h*60+m;return `<li class="${v<hm?'done':''}">${formatTime(t)} · ${v<hm?'Completed':'Scheduled'}</li>`}).join('')}
function formatTime(t){let[h,m]=t.split(':').map(Number),s=h>=12?'PM':'AM';h=h%12||12;return `${h}:${String(m).padStart(2,'0')} ${s}`}
function showRegion(r){$('#detailBody').innerHTML=`<small>REGIONAL PROCUREMENT OPERATIONS</small><h2>${esc(r.employee)}</h2><p><b>${esc(r.name)}</b> · ${regionalState(r.code)==='connected'?'Connected and monitoring approved procurement sources.':'Source connection needs attention.'}</p><div class="detail-section"><h3>PRIMARY RESPONSIBILITY</h3><p>Discover and route relevant ${esc(r.name)} state and local opportunities into ProcessPilot's qualification workflow.</p></div><div class="detail-section"><h3>HANDOFF</h3><p>Qualified opportunities move to the background specialist workforce for analysis, research, proposal, compliance, pricing and outreach preparation.</p></div><div class="detail-section"><h3>EXECUTIVE CONTROL</h3><p>Binding pursuit, pricing, external communication and submission decisions escalate to Opara for final review and approval.</p></div>`;$('#detail').showModal()}
function showQueue(){const items=runtime?.approvals||[];$('#detailBody').innerHTML=`<small>EXECUTIVE OPERATIONS</small><h2>Opara · Chief of Staff / CEO</h2><p>Final authority for review, approval and consequential business decisions.</p><div class="detail-section"><h3>DECISION QUEUE</h3>${items.length?items.map(x=>`<article class="decision"><b>${esc(x.title)}</b><p>${esc(x.summary||'Decision required')}</p><small>${esc(String(x.approval_type||'approval').replaceAll('_',' '))}</small></article>`).join(''):'<p>No verified decisions are waiting.</p>'}</div><div class="detail-section"><h3>AUTHORITY</h3><p>Approve or decline pursuits, external outreach, pricing commitments, contractual risk and final submissions.</p></div>`;$('#detail').showModal()}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'});}
async function load(){try{[registry,jurisdictions]=await Promise.all([json('/data/agents.json'),json('/data/jurisdictions.json')]);runtime=await json('/api/status');renderRegional();renderStatus();renderCycles()}catch(e){console.error(e);$('#systemState').textContent='Runtime unavailable';$('#availability').textContent='ERROR'}}
$('#closeDetail').onclick=()=>$('#detail').close();$('#chief').onclick=showQueue;$('#openQueue').onclick=showQueue;setInterval(clock,1000);clock();load();setInterval(load,30000);