import {db,insertEvent,createWork} from '../../lib/db.js';
import {sendApprovedDraft} from '../../lib/gmail.js';
function authorized(req){const s=process.env.PROCESSPILOT_RUN_SECRET;return Boolean(s&&req.headers.authorization===`Bearer ${s}`);}
async function patch(table,id,body){return db(`${table}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(body)});}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!authorized(req))return res.status(401).json({error:'Unauthorized'});let {approval_id,decision,note=''}=req.body||{};if(decision==='rejected')decision='declined';if(!approval_id||!['approved','declined','returned'].includes(decision))return res.status(400).json({error:'approval_id and valid decision required'});try{const rows=await db(`approvals?id=eq.${encodeURIComponent(approval_id)}&status=eq.pending&select=*&limit=1`),approval=rows?.[0];if(!approval)return res.status(404).json({error:'Pending approval not found'});const now=new Date().toISOString();let externalAction=null;
if(approval.approval_type==='pursuit_decision'&&decision==='approved'){await patch('opportunities',approval.opportunity_id,{status:'approved'});if(approval.work_packet_id)await patch('work_packets',approval.work_packet_id,{status:'completed',completed_at:now});await createWork({opportunity_id:approval.opportunity_id,workflow_id:'opportunity-to-proposal',current_agent_id:'agency-researcher',current_stage:'capture',status:'queued',priority:70,input:{approved_by:'Opara',approval_id:approval.id}});}
else if(approval.approval_type==='proposal_submission'&&decision==='approved'){if(approval.work_packet_id)await patch('work_packets',approval.work_packet_id,{status:'completed',completed_at:now,output:{proposal_package_approved:true,approval_id:approval.id}});await patch('opportunities',approval.opportunity_id,{status:'proposal'});externalAction='Proposal package approved; no external submission was performed.';}
else if(approval.approval_type==='external_outreach'&&decision==='approved'){const p=approval.payload||{};if(!p.gmail_draft_id||!p.prospect_id)throw new Error('Approved outreach is missing Gmail draft or prospect linkage');const sent=await sendApprovedDraft(p.gmail_draft_id,{approved:true});await patch('outreach_prospects',p.prospect_id,{status:'contacted',last_contacted_at:now,metadata:{...(p.metadata||{}),gmail_message_id:sent?.id||null,approval_id:approval.id}});externalAction='Approved Gmail outreach sent.';await insertEvent({agent_id:'outreach-agent',event_type:'external_outreach_sent',message:`Approved outreach was sent to ${p.to||'the public business contact'}.`,severity:'success',verified:true,source:'gmail-approved-send',metadata:{approval_id:approval.id,prospect_id:p.prospect_id,message_id:sent?.id||null}});}
else if(decision==='declined'){if(approval.opportunity_id&&approval.approval_type==='pursuit_decision')await patch('opportunities',approval.opportunity_id,{status:'declined'});if(approval.work_packet_id)await patch('work_packets',approval.work_packet_id,{status:'completed',completed_at:now,output:{decision:'declined'}});if(approval.approval_type==='external_outreach'&&approval.payload?.prospect_id)await patch('outreach_prospects',approval.payload.prospect_id,{status:'qualified'});}
else if(decision==='returned'){if(approval.work_packet_id){const proposal=approval.approval_type==='proposal_submission';await patch('work_packets',approval.work_packet_id,{status:'queued',current_stage:proposal?'proposal':'qualify',current_agent_id:proposal?'proposal-manager':'opportunity-analyst',error:null});}if(approval.approval_type==='external_outreach'&&approval.payload?.prospect_id)await patch('outreach_prospects',approval.payload.prospect_id,{status:'qualified'});}
await patch('approvals',approval.id,{status:decision,decision_by:'Opara',decision_note:note,decided_at:now});await insertEvent({agent_id:'executive-brief',event_type:'approval_decided',message:`Opara ${decision} ${approval.title}.`,severity:decision==='approved'?'success':'warning',verified:true,source:'owner-action',opportunity_id:approval.opportunity_id,work_packet_id:approval.work_packet_id,metadata:{approval_id:approval.id,note,external_action:externalAction}});return res.status(200).json({ok:true,decision,externalAction});}catch(e){return res.status(500).json({error:e.message});}}
