import {db} from '../../lib/db.js';
import {runQueuedWork,processRetryableFailures} from '../../lib/agent-runner.js';
import {scanGmailForRfps} from '../../lib/gmail-intake.js';
import {checkSourceHealth} from '../../lib/source-health.js';
import {collectAllPortals} from '../../lib/portal-collector.js';
const RUN_HOURS=new Set(['08','10','12','14','16']);
function chicagoParts(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'2-digit',minute:'2-digit',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return Object.fromEntries(parts.map(p=>[p.type,p.value]));}
async function event(agentId,type,message,metadata={}){return db('activity_events',{method:'POST',body:JSON.stringify({agent_id:agentId,event_type:type,message,severity:'info',source:'scheduled-cycle',verified:true,metadata})});}
export default async function handler(req,res){const auth=req.headers.authorization;const allowed=(process.env.CRON_SECRET&&auth===`Bearer ${process.env.CRON_SECRET}`)||(process.env.PROCESSPILOT_RUN_SECRET&&auth===`Bearer ${process.env.PROCESSPILOT_RUN_SECRET}`);if(!allowed)return res.status(401).json({error:'Unauthorized'});const t=chicagoParts();if(!RUN_HOURS.has(t.hour)||Number(t.minute)>14)return res.status(200).json({ran:false,reason:'off-cycle',chicago:`${t.year}-${t.month}-${t.day} ${t.hour}:${t.minute}`});const cycleKey=`${t.year}-${t.month}-${t.day}T${t.hour}`;const existing=await db(`activity_events?event_type=eq.cycle_started&metadata->>cycle_key=eq.${encodeURIComponent(cycleKey)}&select=id&limit=1`);if(existing?.length)return res.status(200).json({ran:false,reason:'already-ran',cycleKey});await event('opportunity-scout','cycle_started',`Procurement operating cycle ${t.hour}:00 CT started.`,{cycle_key:cycleKey});const sourceHealth=await checkSourceHealth();let portals={ingested:0,results:[]};try{portals=await collectAllPortals();}catch(e){await event('source-monitor','portal_collection_failed','Approved portal collection failed during scheduled cycle.',{cycle_key:cycleKey,error:e.message});portals={ingested:0,error:e.message,results:[]};}let intake={checked:0,ingested:0,results:[]};try{intake=await scanGmailForRfps({limit:10});}catch(e){await event('opportunity-scout','gmail_intake_failed','Gmail procurement intake failed during scheduled cycle.',{cycle_key:cycleKey,error:e.message});intake={error:e.message};}let retried={length:0};try{retried=await processRetryableFailures(5);}catch(e){await event('executive-brief','retry_processing_failed','Retry processing failed during scheduled cycle.',{cycle_key:cycleKey,error:e.message});}
const results=await runQueuedWork(2);await event('executive-brief','cycle_completed',`Operating cycle ${t.hour}:00 CT completed.`,{cycle_key:cycleKey,portal_intake:{ingested:portals.ingested||0},gmail_intake:{checked:intake.checked||0,ingested:intake.ingested||0},retried:retried.length,work_results:results});return res.status(200).json({ran:true,cycleKey,sourceHealth,portals:{ingested:portals.ingested||0,error:portals.error||null,results:portals.results||[]},intake:{checked:intake.checked||0,ingested:intake.ingested||0,error:intake.error||null},retried,results});}
