import fs from 'node:fs';
import path from 'node:path';
import {runAgentModel} from './ai.js';
import {db,createAgentRun,updateAgentRun,createArtifact,createApproval,createWork,insertEvent,updateWork,listCompanyKnowledge,listDocumentTemplates} from './db.js';
import {requiresApproval} from './governance.js';
function registry(){return JSON.parse(fs.readFileSync(path.join(process.cwd(),'data','agents.json'),'utf8')).agents;}
function byId(id){const a=registry().find(x=>x.id===id);if(!a)throw new Error(`Unknown agent ${id}`);return a;}
function parseJson(text){try{return JSON.parse(text);}catch{const m=String(text).match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):{summary:text};}catch{return {summary:text};}}}
const MAX_RETRY_ATTEMPTS=3;
const STAGES={qualify:['opportunity-analyst','fit-scorer','bid-no-bid'],capture:['agency-researcher','incumbent-researcher','partner-researcher','capture-analyst','deadline-monitor'],proposal:['proposal-manager','requirements-analyst','compliance-matrix','registration-analyst','past-performance','proposal-writer','technical-writer','executive-writer','proposal-reviewer','clause-analyst'],pricing:['pricing-analyst','margin-reviewer'],submission_review:[],delivery:['contracts-reviewer'],delivery_kickoff:['delivery-manager','performance-analyst']};
async function loadOpportunity(id){const rows=await db(`opportunities?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);return rows?.[0]||null;}
async function loadArtifacts(id){return db(`artifacts?opportunity_id=eq.${encodeURIComponent(id)}&select=artifact_type,title,content,status,created_at&order=created_at.asc`);}
async function event(agentId,eventType,message,{opportunityId,workPacketId,severity='info',metadata={}}={}){await insertEvent({agent_id:agentId,event_type:eventType,message,severity,verified:true,source:'agent-runtime',opportunity_id:opportunityId||null,work_packet_id:workPacketId||null,metadata});}
async function contextFor(agent){const knowledge=await listCompanyKnowledge(100);let templates=[];if(/proposal|writer|compliance|pricing|contract|outreach|teaming/i.test(`${agent.id} ${agent.department}`))templates=await listDocumentTemplates(/contract/i.test(agent.id)?'contract':null);return {approved_company_knowledge:knowledge,approved_templates:templates};}
function promptFor(agent,opportunity,artifacts,companyContext){return {opportunity,prior_artifacts:artifacts,...companyContext,required_output:{format:'json',fields:['summary','findings','recommendation','risks','next_actions']},instructions:'Use approved_company_knowledge as the authoritative source for ProcessPilot facts. Use opportunity documents and prior artifacts for solicitation facts. Never invent company capabilities, past performance, certifications, pricing, buyer facts, deadlines, contacts, or submission facts. A knowledge item approved_for_external_use=false may guide internal reasoning but must not be represented externally as a marketing claim. Missing evidence must be identified explicitly. External email, submission, signature, pricing commitment and contract acceptance require Opara approval. Fit Scorer must include a numeric fit_score from 0 to 100 and fit_rationale string.'};}
function fitFields(parsed){const score=Number(parsed?.fit_score??parsed?.findings?.provisional_fit_score??parsed?.findings?.fit_score??parsed?.recommendation?.fit_score);return {score:Number.isFinite(score)?Math.max(0,Math.min(100,score)):null,rationale:String(parsed?.fit_rationale||parsed?.summary||parsed?.recommendation?.rationale||'').slice(0,5000)};}
async function executeAgent(agentId,packet,opportunity){const agent=byId(agentId),artifacts=await loadArtifacts(opportunity.id),companyContext=await contextFor(agent),started=Date.now();const runs=await createAgentRun({work_packet_id:packet.id,opportunity_id:opportunity.id,agent_id:agent.id,department:agent.department,status:'running',input:{stage:packet.current_stage,opportunity_id:opportunity.id,knowledge_items:companyContext.approved_company_knowledge.length},started_at:new Date().toISOString()});const run=runs?.[0];await updateWork(packet.id,{status:'running',current_agent_id:agent.id,started_at:packet.started_at||new Date().toISOString()});await event(agent.id,'agent_started',`${agent.name} started work on ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id});try{const result=await runAgentModel({agent,input:promptFor(agent,opportunity,artifacts,companyContext)}),parsed=parseJson(result.output);await createArtifact({opportunity_id:opportunity.id,work_packet_id:packet.id,agent_run_id:run?.id||null,artifact_type:agent.id,title:`${agent.name} output`,content:parsed,status:'draft'});if(agent.id==='fit-scorer'){const f=fitFields(parsed);if(f.score!==null)await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({fit_score:f.score,fit_rationale:f.rationale})});}if(run?.id)await updateAgentRun(run.id,{status:'completed',model:result.model,output:parsed,completed_at:new Date().toISOString()});await event(agent.id,'agent_completed',`${agent.name} completed its assigned analysis.`,{opportunityId:opportunity.id,workPacketId:packet.id,metadata:{model:result.model,usage:result.usage||null,duration_ms:Date.now()-started,knowledge_grounded:true}});return parsed;}catch(e){if(run?.id)await updateAgentRun(run.id,{status:'failed',output:{error:e.message},completed_at:new Date().toISOString()});await updateWork(packet.id,{status:'failed',error:e.message});await recordFailure({workPacketId:packet.id,opportunityId:opportunity.id,agentId:agent.id,operation:'agent_execution',error:e.message});await event(agent.id,'agent_failed',`${agent.name} failed: ${e.message}`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'error'});throw e;}}
// Bounded-retry bookkeeping: attempt count is derived from the highest
// prior attempt already recorded for this exact work packet + agent +
// operation (any status), not hardcoded to 1, so repeated failures actually
// escalate toward MAX_RETRY_ATTEMPTS instead of resetting every time.
// Exponential backoff (15min * 2^(attempt-1), capped at 4h) between tries.
async function recordFailure({workPacketId,opportunityId,agentId,operation,error}){
  const prior=await db(`runtime_failures?work_packet_id=eq.${workPacketId}&agent_id=eq.${encodeURIComponent(agentId)}&operation=eq.${encodeURIComponent(operation)}&select=attempt&order=attempt.desc&limit=1`).catch(()=>[]);
  const attempt=(prior?.[0]?.attempt||0)+1;
  const backoffMs=Math.min(4*60*60*1000,15*60*1000*Math.pow(2,attempt-1));
  await db('runtime_failures',{method:'POST',body:JSON.stringify({work_packet_id:workPacketId,opportunity_id:opportunityId,agent_id:agentId,operation,error,attempt,status:attempt>=MAX_RETRY_ATTEMPTS?'terminal':'open',next_retry_at:new Date(Date.now()+backoffMs).toISOString()})}).catch(()=>null);
  if(attempt>=MAX_RETRY_ATTEMPTS)await event(agentId,'retry_exhausted',`${agentId} failed ${attempt} times on work packet ${workPacketId} and will not be retried automatically. Manual review is required.`,{opportunityId,workPacketId,severity:'error'});
}
// Processes runtime_failures rows whose retry window has arrived: requeues
// the associated work packet (bounded by MAX_RETRY_ATTEMPTS, enforced when
// the failure was recorded) and marks the failure row consumed so it is
// never retried twice. Rows already marked 'terminal' are never picked up
// here -- they require manual intervention, matching the activity event
// logged when the threshold was reached.
export async function processRetryableFailures(limit=5){
  const due=await db(`runtime_failures?status=eq.open&next_retry_at=lte.${encodeURIComponent(new Date().toISOString())}&select=*&order=next_retry_at.asc&limit=${limit}`).catch(()=>[]);
  const results=[];
  for(const failure of due||[]){
    try{
      await db(`work_packets?id=eq.${encodeURIComponent(failure.work_packet_id)}`,{method:'PATCH',body:JSON.stringify({status:'queued',error:null})});
      await db(`runtime_failures?id=eq.${encodeURIComponent(failure.id)}`,{method:'PATCH',body:JSON.stringify({status:'retried'})});
      await event(failure.agent_id,'retry_requeued',`Work packet ${failure.work_packet_id} requeued for retry attempt ${failure.attempt} after: ${failure.error}`,{opportunityId:failure.opportunity_id,workPacketId:failure.work_packet_id,severity:'warning'});
      results.push({id:failure.id,work_packet_id:failure.work_packet_id,status:'requeued'});
    }catch(e){results.push({id:failure.id,status:'retry_failed',error:e.message});}
  }
  return results;
}
async function requestPursuit(packet,opportunity){
  if(!requiresApproval('pursuit_decision')){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{qualification_complete:true,auto_approved:true}});await event('executive-brief','governance_auto_approved',`Pursuit decision for ${opportunity.title} proceeded without a human checkpoint per governance.json (pursuit_decision=automatic). Downstream capture work was not queued automatically -- this bypass path is untested and requires manual follow-up.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});return;}
  const artifacts=await loadArtifacts(opportunity.id),bid=artifacts.filter(a=>a.artifact_type==='bid-no-bid').at(-1)?.content||{},fit=artifacts.filter(a=>a.artifact_type==='fit-scorer').at(-1)?.content||{};const existing=await db(`approvals?work_packet_id=eq.${packet.id}&approval_type=eq.pursuit_decision&status=eq.pending&select=id&limit=1`);if(!existing?.length)await createApproval({opportunity_id:opportunity.id,work_packet_id:packet.id,requested_by_agent_id:'executive-brief',approval_type:'pursuit_decision',title:`Pursuit decision: ${opportunity.title}`,summary:bid.summary||bid.recommendation||'Qualification analysis completed.',payload:{fit,decision:bid},status:'pending'});await updateWork(packet.id,{status:'waiting_approval',current_agent_id:'executive-brief',current_stage:'pursuit_review',output:{qualification_complete:true}});await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({status:'pursuit_review'})});await event('executive-brief','approval_requested',`Chief of Staff review requested for ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});}
async function requestSubmission(packet,opportunity){
  if(!requiresApproval('submit_response')){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{proposal_package_approved:true,auto_approved:true}});await event('proposal-manager','governance_auto_approved',`Proposal submission for ${opportunity.title} proceeded without a human checkpoint per governance.json (submit_response=automatic). No external submission was performed -- this bypass path is untested and requires manual follow-up.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});return;}
  const artifacts=await loadArtifacts(opportunity.id),existing=await db(`approvals?work_packet_id=eq.${packet.id}&approval_type=eq.proposal_submission&status=eq.pending&select=id&limit=1`);if(!existing?.length)await createApproval({opportunity_id:opportunity.id,work_packet_id:packet.id,requested_by_agent_id:'proposal-manager',approval_type:'proposal_submission',title:`Proposal package approval: ${opportunity.title}`,summary:'Proposal, compliance, contract-risk and pricing draft stages are complete. Human approval is required before any external submission.',payload:{artifact_count:artifacts.length},status:'pending'});await updateWork(packet.id,{status:'waiting_approval',current_agent_id:'executive-brief',current_stage:'submission_review'});await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({status:'proposal'})});await event('proposal-manager','approval_requested',`Final proposal package requires Opara approval for ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});}
async function requestContractAcceptance(packet,opportunity){
  if(!requiresApproval('accept_contract')){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{contract_accepted:true,auto_approved:true}});await event('contracts-reviewer','governance_auto_approved',`Contract acceptance for ${opportunity.title} proceeded without a human checkpoint per governance.json (accept_contract=automatic). Delivery kickoff was not queued automatically -- this bypass path is untested and requires manual follow-up.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});return;}
  const artifacts=await loadArtifacts(opportunity.id);
  const contractReview=artifacts.filter(a=>a.artifact_type==='contracts-reviewer').at(-1)?.content||{};
  const existing=await db(`approvals?work_packet_id=eq.${packet.id}&approval_type=eq.contract_acceptance&status=eq.pending&select=id&limit=1`);
  if(!existing?.length)await createApproval({opportunity_id:opportunity.id,work_packet_id:packet.id,requested_by_agent_id:'contracts-reviewer',approval_type:'contract_acceptance',title:`Contract acceptance: ${opportunity.title}`,summary:contractReview.summary||contractReview.recommendation||'Contract review is complete. Executive sign-off is required before delivery kickoff begins.',payload:{contract_review:contractReview},status:'pending'});
  await updateWork(packet.id,{status:'waiting_approval',current_agent_id:'executive-brief',current_stage:'contract_acceptance_review'});
  await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({status:'contract_review'})});
  await event('contracts-reviewer','approval_requested',`Chief of Staff review requested for contract acceptance on ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});
}
async function requestPricingCommitment(packet,opportunity){
  if(!requiresApproval('commit_price')){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{pricing_committed:true,auto_approved:true}});await event('margin-reviewer','governance_auto_approved',`Pricing commitment for ${opportunity.title} proceeded without a human checkpoint per governance.json (commit_price=automatic). Final proposal review was not queued automatically -- this bypass path is untested and requires manual follow-up.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});return;}
  const artifacts=await loadArtifacts(opportunity.id);
  const pricing=artifacts.filter(a=>a.artifact_type==='pricing-analyst').at(-1)?.content||{};
  const margin=artifacts.filter(a=>a.artifact_type==='margin-reviewer').at(-1)?.content||{};
  const existing=await db(`approvals?work_packet_id=eq.${packet.id}&approval_type=eq.pricing_commitment&status=eq.pending&select=id&limit=1`);
  if(!existing?.length)await createApproval({opportunity_id:opportunity.id,work_packet_id:packet.id,requested_by_agent_id:'margin-reviewer',approval_type:'pricing_commitment',title:`Pricing commitment: ${opportunity.title}`,summary:margin.summary||pricing.summary||'Pricing model and margin/risk review are complete. Executive approval is required before the price is committed in the proposal package.',payload:{pricing,margin},status:'pending'});
  await updateWork(packet.id,{status:'waiting_approval',current_agent_id:'executive-brief',current_stage:'pricing_review'});
  await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({status:'pricing_review'})});
  await event('margin-reviewer','approval_requested',`Chief of Staff review requested for pricing commitment on ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'warning'});
}
export async function runWorkPacket(packet){const opportunity=await loadOpportunity(packet.opportunity_id);if(!opportunity)throw new Error('Opportunity not found');const stage=packet.current_stage||'qualify',sequence=STAGES[stage];if(!(stage in STAGES))throw new Error(`Unsupported stage ${stage}`);for(const agentId of sequence)await executeAgent(agentId,packet,opportunity);if(stage==='qualify'){await requestPursuit(packet,opportunity);return {status:'waiting_approval',stage};}if(stage==='capture'){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{stage_complete:stage}});await createWork({opportunity_id:opportunity.id,workflow_id:'opportunity-to-proposal',current_agent_id:'proposal-manager',current_stage:'proposal',status:'queued',priority:65,input:{from_stage:'capture'}});await db(`opportunities?id=eq.${opportunity.id}`,{method:'PATCH',body:JSON.stringify({status:'research'})});await event('capture-analyst','stage_completed',`Capture stage completed for ${opportunity.title}; proposal work queued.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'success'});return {status:'completed',stage,next:'proposal'};}
if(stage==='proposal'){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{stage_complete:stage}});await createWork({opportunity_id:opportunity.id,workflow_id:'opportunity-to-proposal',current_agent_id:'pricing-analyst',current_stage:'pricing',status:'queued',priority:66,input:{from_stage:'proposal'}});await event('proposal-manager','stage_completed',`Proposal content stage completed for ${opportunity.title}; pricing work queued.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'success'});return {status:'completed',stage,next:'pricing'};}
if(stage==='pricing'){await requestPricingCommitment(packet,opportunity);return {status:'waiting_approval',stage};}
if(stage==='submission_review'){await requestSubmission(packet,opportunity);return {status:'waiting_approval',stage};}
if(stage==='delivery'){await requestContractAcceptance(packet,opportunity);return {status:'waiting_approval',stage};}
if(stage==='delivery_kickoff'){await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{stage_complete:stage}});await event('delivery-manager','stage_completed',`Delivery kickoff completed for ${opportunity.title} following approved contract acceptance.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'success'});return {status:'completed',stage};}
await updateWork(packet.id,{status:'completed',completed_at:new Date().toISOString(),output:{stage_complete:stage}});await event(sequence.at(-1),'stage_completed',`${stage} stage completed for ${opportunity.title}.`,{opportunityId:opportunity.id,workPacketId:packet.id,severity:'success'});return {status:'completed',stage};}
export async function runQueuedWork(limit=1){const packets=await db(`work_packets?status=eq.queued&select=*&order=priority.desc,created_at.asc&limit=${limit}`),results=[];for(const packet of packets||[]){try{results.push({id:packet.id,...await runWorkPacket(packet)});}catch(e){results.push({id:packet.id,status:'failed',error:e.message});}}return results;}
