const ALLOWED_SENDERS=new Set(['eo@processpilottech.com','contracts@processpilottech.com']);

export function gmailConfigured(){return Boolean(process.env.GMAIL_CLIENT_ID&&process.env.GMAIL_CLIENT_SECRET&&process.env.GMAIL_REFRESH_TOKEN)}
export function assertAllowedSender(sender){const value=String(sender||'').toLowerCase();if(!ALLOWED_SENDERS.has(value))throw new Error('Sender is not approved for ProcessPilot');return value}
export async function gmailAccessToken(){if(!gmailConfigured())throw new Error('Gmail OAuth is not configured');const body=new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET,refresh_token:process.env.GMAIL_REFRESH_TOKEN,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok||!data.access_token)throw new Error('Unable to refresh Gmail access token');return data.access_token}
export async function gmailRequest(path,options={}){const token=await gmailAccessToken();const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{...options,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Gmail API request failed: ${r.status}`);return data}
export async function getGmailProfile(){return gmailRequest('/profile')}
export async function createDraft({from,to,subject,body}){const sender=assertAllowedSender(from);const raw=`From: ${sender}\r\nTo: ${to}\r\nSubject: ${subject}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${body}`;const encoded=Buffer.from(raw).toString('base64url');return gmailRequest('/drafts',{method:'POST',body:JSON.stringify({message:{raw:encoded}})})}
export async function sendApprovedDraft(draftId,{approved=false}={}){if(!approved)throw new Error('Opara approval is required before external email is sent');return gmailRequest('/drafts/send',{method:'POST',body:JSON.stringify({id:draftId})})}
