import {getIntegrationCredential} from './supabase-server.js';

const ALLOWED_SENDERS=new Set(['eo@processpilottech.com','contracts@processpilottech.com']);
export function gmailConfigured(){return Boolean(process.env.GMAIL_CLIENT_ID&&process.env.GMAIL_CLIENT_SECRET&&process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY)}
export function assertAllowedSender(sender){const value=String(sender||'').toLowerCase();if(!ALLOWED_SENDERS.has(value))throw new Error('Sender is not approved for ProcessPilot');return value}
async function refreshToken(){if(process.env.GMAIL_REFRESH_TOKEN)return process.env.GMAIL_REFRESH_TOKEN;const stored=await getIntegrationCredential('gmail_refresh_token');if(!stored?.secret_value)throw new Error('Gmail OAuth refresh token is not stored');return stored.secret_value;}
export async function gmailAccessToken(){if(!gmailConfigured()&&!process.env.GMAIL_REFRESH_TOKEN)throw new Error('Gmail OAuth is not configured');const token=await refreshToken();const body=new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET,refresh_token:token,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok||!data.access_token)throw new Error('Unable to refresh Gmail access token');return data.access_token;}
export async function gmailRequest(path,options={}){const token=await gmailAccessToken();const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{...options,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Gmail API request failed: ${r.status}`);return data;}
export async function getGmailProfile(){return gmailRequest('/profile')}
export async function searchMessages(query,maxResults=20){return gmailRequest(`/messages?q=${encodeURIComponent(query)}&maxResults=${Math.min(maxResults,50)}`)}
export async function getMessage(id){return gmailRequest(`/messages/${encodeURIComponent(id)}?format=full`)}
function decode(data=''){try{return Buffer.from(data,'base64url').toString('utf8');}catch{return '';}}
export function messageText(message){const headers=Object.fromEntries((message.payload?.headers||[]).map(h=>[String(h.name).toLowerCase(),h.value]));const chunks=[];function walk(part){if(part?.mimeType==='text/plain'&&part.body?.data)chunks.push(decode(part.body.data));for(const p of part?.parts||[])walk(p);}walk(message.payload);if(!chunks.length&&message.payload?.body?.data)chunks.push(decode(message.payload.body.data));return {id:message.id,threadId:message.threadId,subject:headers.subject||'',from:headers.from||'',to:headers.to||'',date:headers.date||'',body:chunks.join('\n').slice(0,30000)};}
export async function createDraft({from,to,subject,body}){const sender=assertAllowedSender(from);const raw=`From: ${sender}\r\nTo: ${to}\r\nSubject: ${subject}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${body}`;const encoded=Buffer.from(raw).toString('base64url');return gmailRequest('/drafts',{method:'POST',body:JSON.stringify({message:{raw:encoded}})});}
export async function sendApprovedDraft(draftId,{approved=false}={}){if(!approved)throw new Error('Opara approval is required before external email is sent');return gmailRequest('/drafts/send',{method:'POST',body:JSON.stringify({id:draftId})});}
